version: '3.1'
services:
  es00:
    container_name: es00
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    volumes:
      - ./es00/data:/usr/share/elasticsearch/data
      - ./es00/logs:/var/log
    environment:
      - cluster.name=elastic
      - node.name=es00
      - cluster.initial_master_nodes=es00,es01
      - bootstrap.memory_lock=true
      - discovery.seed_hosts=es01
      # - "ES_JAVA_OPTS=8-:-Xms1G 8-:-Xmx1G 8-:-XX:+UseG1GC"
      - "JAVA_TOOL_OPTIONS=8-:-Xms1G 8-:-Xmx1G 8-:-XX:+UseG1GC"
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - elastic
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=elastic
      - cluster.initial_master_nodes=es00,es01
      - bootstrap.memory_lock=true
      # - "ES_JAVA_OPTS=8-:-Xms1G 8-:-Xmx1G 8-:-XX:+UseG1GC"
      - "JAVA_TOOL_OPTIONS=8-:-Xms1G 8-:-Xmx1G 8-:-XX:+UseG1GC"
      - discovery.seed_hosts=es00
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - network.host=_eth0_
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    volumes:
      - ./es01/data:/usr/share/elasticsearch/data
      - ./es01/logs:/var/log
    networks:
      - elastic
    ports:
      - 9201:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.1
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://es00:9200/
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/logs:/var/log
    ulimits:
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    networks:
      - elastic
  # apmserver:
  #   container_name: apmserver
  #   image: docker.elastic.co/apm/apm-server:7.8.1
  #   command: --strict.perms=false
  #   ports:
  #     - 8200:8200
  #     - 8201:8200
  #   environment:
  #     - apm-server.host=0.0.0.0
  #     - setup.kibana.host=kibana:5601
  #     - output.elasticsearch.hosts=["es00:9200"]
  #   volumes:
  #     - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
  #   networks:
  #       - elastic

networks:
  elastic:
