version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    # restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/node_down.yml:/etc/prometheus/node_down.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
    #volumes:
        #  - grafana:
