version: '3.8'
services:
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    container_name: opendistro_kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://192.168.1.156:9200
      ELASTICSEARCH_HOSTS: https://192.168.1.156:9200
    networks:
      - opendistro

volumes:
  opendistro_0:

networks:
  opendistro:
