version: '3.8'
services:
  opendistro_0:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: opendistro_0
    environment:
      - cluster.name=opendistro
      - node.name=opendistro_0
      - discovery.seed_hosts=opendistro_1,opendistro_0
      - cluster.initial_master_nodes=opendistro_1,opendistro_0
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - ./opendistro_0/data:/usr/share/elasticsearch/data
      - ./opendistro_0/logs:/var/log
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opendistro
  opendistro_1:
    image: amazon/opendistro-for-elasticsearch:1.13.2
    container_name: opendistro_1
    environment:
      - cluster.name=opendistro
      - node.name=opendistro_1
      - discovery.seed_hosts=opendistro_1,opendistro_0
      - cluster.initial_master_nodes=opendistro_1,opendistro_0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opendistro_1/data:/usr/share/elasticsearch/data
      - ./opendistro_1/logs:/var/log
    networks:
      - opendistro
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.13.2
    container_name: opendistro_kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://opendistro_0:9200
      ELASTICSEARCH_HOSTS: https://opendistro_0:9200
    networks:
      - opendistro

volumes:
  opendistro_0:
  opendistro_1:

networks:
  opendistro:
