# docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo -e POSTGRES_DB=postgres --name db postgres:10
# docker run -p 8069:8069 --name odoo --link db:db -t odoo
# docker exec -ti odoo /bin/bash 
# odoo -i base -d odoo --stop-after-init --db_host=postgre -r odoo -w odoo
version: '3.1'
services:
  postgre:
    image: postgres:10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    ports:
      - 5432:5432
    networks:
      - odoonetworks
  odoo:
    image: odoo:12.0
    depends_on:
      - postgre
    ports:
      - 8069:8069
    environment:
      - HOST=postgre
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoonetworks

networks:
  odoonetworks:
