cluster.name: opendistro
node.name: node00
path.data: /Volumes/sm/repos/opendistro_0/data
path.logs: /Volumes/sm/repos/opendistro_0/logs
bootstrap.memory_lock: true
network.host: 127.0.0.1
network.publish_host: 127.0.0.1
transport.host: 127.0.0.1
http.port: 9200
transport.tcp.port: 9300
http.cors.enabled: true
http.cors.allow-origin: /.*/ # 所有
discovery.seed_hosts: ["127.0.0.1", "[::1]"]
cluster.initial_master_nodes: ["node00"]
gateway.recover_after_nodes: 1
action.destructive_requires_name: true
opendistro_security.disabled: true
